### ISSUE TITLE
In Debian text mode some characters can't be displayed

### ISSUE THREAD

**Issue by trn1ty** [unknownblueguy6/MineSweeper#4]
This is probably because you used some special characters or something. I'll try to include a picture of how it looks when I can take a picture.

If you're using Ubuntu or something you can get to textmode by pressing CTRL+ALT+F1 and return to the desktop with CTRL+ALT+F7.

**Comment by BlitzKraft** [comment]
That's the console and I am able to reproduce this. As you mentioned, it is expected behaviour. It can be fixed by using `fbterm`, or setting the console font. To set the console font, refer to the documentation for your distro. 

A true fix would be detecting that the program is running in a `vt` and not a `pty` and use a different character set. Detecting a `vt` can be done using the  `consoletype` command.

**Comment by unknownblueguy6** [comment]
Hey @BlitzKraft, thanks for suggesting a solution :+1: . 
Is there any way I can set the console font during the setup phase, in order to display the correct characters?

**Comment by BlitzKraft** [comment]
The console font can only be changed by the root user. I don't think it's a good idea to deal with that in this program. However, there can be an alternative character set. This is an easy, but non-trivial change. The special character for mines is not ascii compatible and will not be displayed in most default consoles. 

It seems that there are some additional characters that may not work in consoles - one example I found was the vertical line ends in the seven segment display for the number of mines. 

So, my proposed solution is to use a single string for setting the characters. Then call them by their index. This way there there can be just one check on start-up (for pty/vt). Character sets can be changed easily by most people too. 

My proposed change is easy, but non-trivial. What do you think, @unknownblueguy6 ?

**Comment by unknownblueguy6** [comment]
The change seems easy to implement. How would I check whether a character is supported in a `pty` or `vt` environment, and we also need to consider alternate characters, which would change the way it looks. Also, what do you mean by the vertical line ending in the seven segment display?

**Comment by BlitzKraft** [comment]
In a vt environment, usually the 127 ascii characters are sure to be displayed. Anything else depends on the disto/user/settings. Single pipe drawing characters *should* be fine. 

This "╻"  character is what is not being rendered in the vt. Or at least, my vt. This character is the vertical end of the 7-segment display.  

There isn't a universal check. From the program side, we can only check if it's a vt or not.

**Comment by BlitzKraft** [comment]
@unknownblueguy6 This might fit better under a "feature request" label, than a bug. It is expected behaviour, and changes are only visual/font related. It also doesn't affect the game functionally.

**Comment by unknownblueguy6** [comment]
So if we can only check for a vt, then I guess there is no point in adding an exception for all the distros right? Changed the label to enhancement rather than a bug, thanks.

**Comment by BlitzKraft** [comment]
That's correct, this is not distro dependent. 

My suggestion for the characters - use `|` for vertical and `-` for horizontal segments in the mine count. `F` for flagging a mine, `*` for the mines. These are the only non-ascii characters I believe.
